### PR TITLE
fix: Statistics for missing manual and/or automated tests should be separated

### PR DESCRIPTION
**Pull request by lfvdavid**
Statistics for missing manual and/or automated tests should be separated.

Investigate and fix output of total missing tests (automated and manual)

### CODE REVIEW

**Comment by lfvjimisola** [comment]
@lfvdavid Build fails, so setting to draft.

**Comment by lfvdavid** [comment]
@lfvjimisola @lfvbarcus 

I feel like this PR is completed, added skip tag to two tests in the `test_statistics_generator` that i suspect have errors in the testdata, all checks passed now.

There is an open [issue](https://github.com/Luftfartsverket/reqstool-client/issues/29) on validating and rewriting the test data or tests in question if needed.

Opened another [issue](https://github.com/Luftfartsverket/reqstool-client/issues/31) to work on the total statistics of the report as we discussed.

**Comment by lfvjimisola** [comment]
> @lfvjimisola @lfvbarcus
> 
> I feel like this PR is completed, added skip tag to two tests in the `test_statistics_generator` that i suspect have errors in the testdata, all checks passed now.
> 
> There is an open [issue](https://github.com/Luftfartsverket/reqstool-client/issues/29) on validating and rewriting the test data or tests in question if needed.
> 
> Opened another [issue](https://github.com/Luftfartsverket/reqstool-client/issues/31) to work on the total statistics of the report as we discussed.

If you and @lfvbarcus ok with this MR then so am I.

**Comment by lfvbarcus** [comment]
I think that this looks fine. I would suggest that we will not publish a new release until the issues metioned in this PR are solved.

**Review by lfvbarcus — APPROVED** [review]

**Pull request merged**
