### PR TITLE
feat: Restructure total statistics in report

### PR DESCRIPTION
**Pull request by lfvdavid**
Restructure the total statistics generated in the report.

Divide statistics into two rows.

One table row for Requirements with:

* total
* verified (all tests passed)
* implemented
* not implemented

Another table row for tests and SVC's:

* Passed
* Failed
* Skipped
* (Total number of SVC's)?
* SVC's missing automated tests
* SVC's missing manual tests(MVR)

### CODE REVIEW

**Comment by lfvdavid** [comment]
Have added sections to total statistics and divided into two tables as listed above.

For now i have not included `Total number of SVC's`, do we want this to be included?
If so i would suggest creating yet another table just for SVC's, that would mean one for requirements, one for tests and one for SVC's

**Comment by lfvjimisola** [comment]
Please provide a screenshot for easier review.

**Comment by lfvdavid** [comment]
Status report:
Screenshot from 2024-03-01 11-28-33

Asciidoc-report:
Screenshot from 2024-03-01 11-28-12

**Comment by lfvdavid** [comment]
Updated screenshots with changes implemented.

Separated Total requirements, an `Implemented and Verified` requirement is not counted as a `Implemented` requirement in the total statistics.

Screenshot from 2024-03-04 10-41-15

Screenshot from 2024-03-04 10-49-45

**Review by lfvbarcus — APPROVED** [review]
I think this looks great! Good work!

**Pull request merged**
